
@startuml
!define C4PlantUML https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include C4PlantUML

Person(cashier, "Кассир", "Обрабатывает платежи")
Person(patient, "Пациент", "Оплачивает услуги")
System_Boundary(payment_system, "Система оплаты") {
    Component(accounting_1c, "1С Бухгалтерия", "Обработка платежей (шифрование)")
    Component(kkt, "ККТ", "Фискализация операций")
    Component(api_gateway, "API Gateway", "Проверка полномочий, шифрование")
}

Rel(patient, cashier, "Оплачивает услуги", "Наличные/Карта")
Rel(cashier, api_gateway, "Передача данных оплаты", "HTTPS")
Rel(api_gateway, accounting_1c, "Регистрирует оплату", "Шифрование")
Rel(accounting_1c, kkt, "Передача данных фискализации", "TCP/IP - OLE")

@enduml